language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install zope.testrunner coverage coveralls
  - pip install -e .[test-app]
script:
  - coverage run -m zope.testrunner --test-path=src --auto-color --auto-progress
  - coverage report
after_success:
  - coveralls
notifications:
  email: false
